version: "3"

services:
  app:
    container_name: exampleapp
    restart: always
    build: .
    ports:
      - "4000:3000"
    links:
      - mongo
    volumes:
      - .:/usr/src/app

  
  mongo:
    container_name: mymongodatabase
    image: mongo:7
    ports: 
      - "27018:27017"
    logging:
      driver: none