version: "3"

services:
  # app:
  #   container_name: exampleapp
  #   restart: always
  #   build: .
  #   ports:
  #     - "4000:3000"
  #   depends_on:
  #     - mongo
  #   volumes:
  #     - .:/usr/src/app

  mongo:
    container_name: mymongodatabase
    image: mongo:latest
    restart: always
    # command: mongorestore -d movies ./db-dump
    environment:
            MONGO_INITDB_DATABASE: movies
    ports:
      - "27018:27017"
    volumes:
      - ./mongorestore.sh:/docker-entrypoint-initdb.d/mongorestore.sh
      - ./dump:/dump


  backend:
    container_name: backend_container
    build:
      context: ./backend
      dockerfile: Dockerfile-backend
    depends_on:
      - mongo
    ports:
      - "3000:3000"

  frontend:
    container_name: frontend_container
    build:
      context: ./frontend
      dockerfile: Dockerfile-frontend
    depends_on:
      - backend
    ports:
      - "4000:4000"

  mongo-express:
    container_name: adminMongo_container
    image: mongo-express:latest
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
    ports:
      - "8081:8081"
    depends_on:
      - mongo

  nginx:
    container_name: nginx_loadbalancer
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    command: ["nginx", "-g", "daemon off;"]
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend